## DISPLAY PANDA DATAFRAMES - selecting rows & columns ##

In [1]:
import pandas as pd

In [9]:
print('Instead of using print, we can also use "DISPLAY"')

Instead of using print, we can also use "DISPLAY"

In [12]:
display("DataFrame_name")

'DataFrame_name'

In [21]:
fruits=pd.read_csv("fruits.csv")
display(fruits)

   Fruits  Prices      Country
0   Apple     1.2       Africa
1  Orange     0.7       Russia
2  Banana     0.9  New Zealand

In [26]:
print("to select columns, create a list")
fruits[['Country','Fruits']]

to select columns, create a list

       Country  Fruits
0       Africa   Apple
1       Russia  Orange
2  New Zealand  Banana

In [27]:
print("to select only ONE column, put the variable name as a string")
fruits["Prices"]

to select only ONE column, put the variable name as a string

0    1.2
1    0.7
2    0.9
Name: Prices, dtype: float64

In [32]:
print("to select rows, use iloc. If multiple rows, the indices must be put in a list first. If ONE row, the index can be put in the index operator directly. Row indexes start with 0 and ends with -1")

to select rows, use iloc. If multiple rows, the indices must be put in a list first. If ONE row, the index can be put in the index operator directly. Row indexes start with 0 and ends with -1

In [64]:
display(fruits)
print("Select row 0, aka 1st row")
(fruits.iloc[0])

   Fruits  Prices      Country
0   Apple     1.2       Africa
1  Orange     0.7       Russia
2  Banana     0.9  New Zealand

Select row 0, aka 1st row

Fruits      Apple
Prices        1.2
Country    Africa
Name: 0, dtype: object

In [65]:
print("Select all rows until BEFORE -1 aka the 2nd last row")
(fruits.iloc[:-1])

Select all rows until BEFORE -1 aka the 2nd last row

   Fruits  Prices Country
0   Apple     1.2  Africa
1  Orange     0.7  Russia

In [72]:
print("Select row 0 to BEFORE row 2")
(fruits.iloc[0:2])

Select row 0 to BEFORE row 2

   Fruits  Prices Country
0   Apple     1.2  Africa
1  Orange     0.7  Russia

In [68]:
print("Select row 0 and row 2, and column 0 and column 2")
fruits.iloc[[0,2],[0,2]]

Select row 0 and row 2, and column 0 and column 2

   Fruits      Country
0   Apple       Africa
2  Banana  New Zealand

In [63]:
print("Select 1st row and 3rd row, keep all columns.")
fruits.iloc[[0,2], :]

Select 1st row and 3rd row, keep all columns.

   Fruits  Prices      Country
0   Apple     1.2       Africa
2  Banana     0.9  New Zealand

In [70]:
print('Select row 0 to BEFORE row 2 from fruits and prices')
fruits[['Fruits','Prices']].iloc[0:2]

Select row 0 to BEFORE row 2 from fruits and prices

   Fruits  Prices
0   Apple     1.2
1  Orange     0.7

## BOOLEAN MASKING - using conditions to identify the data selection ##

In [74]:
display(fruits)

   Fruits  Prices      Country
0   Apple     1.2       Africa
1  Orange     0.7       Russia
2  Banana     0.9  New Zealand

In [80]:
print('Select those with prices > 0.7')
fruits[ (fruits['Prices'] > 0.7) ]

Select those with prices > 0.7

   Fruits  Prices      Country
0   Apple     1.2       Africa
2  Banana     0.9  New Zealand

In [81]:
print('Select those elements which satisfy BOTH conditions using "&". EACH CONDITION MUST BE ENCLOSED IN PARENTHESES ( )')
fruits[ (fruits['Prices'] > 0.7) & (fruits['Country'] == 'New Zealand')]

Select those elements which satisfy BOTH conditions using "&". EACH CONDITION MUST BE ENCLOSED IN PARENTHESES ( )

   Fruits  Prices      Country
2  Banana     0.9  New Zealand

In [83]:
print('Select those elements which satisfy EITHER conditions using "|". EACH CONDITION MUST BE ENCLOSED IN PARENTHESES ( )')
fruits[ (fruits['Prices'] > 0.7) | (fruits['Country'] == 'New Zealand')]

Select those elements which satisfy EITHER conditions using "|". EACH CONDITION MUST BE ENCLOSED IN PARENTHESES ( )

   Fruits  Prices      Country
0   Apple     1.2       Africa
2  Banana     0.9  New Zealand

#### CLASS ACTIVITY 1 ###

In [85]:
import pandas as pd
carmodels = pd.read_csv("car_model.csv")
carmodels

     Year        Make    Model Category
0    2021       Acura      ILX    Sedan
1    2021       Acura      RDX      SUV
2    2021       Acura      TLX    Sedan
3    2021  Alfa Romeo   Giulia    Sedan
4    2021  Alfa Romeo  Stelvio      SUV
..    ...         ...      ...      ...
235  2021       Volvo      V60    Wagon
236  2021  Volkswagen   Tiguan      SUV
237  2021       Volvo     XC40      SUV
238  2021       Volvo     XC60      SUV
239  2021       Volvo     XC90      SUV

[240 rows x 4 columns]

In [87]:
carmodels.shape

(240, 4)

#### CLASS ACTIVITY 2 ###

In [98]:
print('Select the column variable "Make" from the dataframe')
carmodels['Make']

Select the column variable "Make" from the dataframe

0           Acura
1           Acura
2           Acura
3      Alfa Romeo
4      Alfa Romeo
          ...
235         Volvo
236    Volkswagen
237         Volvo
238         Volvo
239         Volvo
Name: Make, Length: 240, dtype: object

In [99]:
print('Select all entries with the value "Audi" in the variable "Make" from the dataframe')
carmodels[carmodels['Make']=='Audi']

Select all entries with the value "Audi" in the variable "Make" from the dataframe

    Year  Make       Model                 Category
5   2021  Audi  A6 allroad                    Wagon
6   2021  Audi          A7                    Sedan
7   2021  Audi          Q3                      SUV
8   2021  Audi          Q5                      SUV
9   2021  Audi          Q8                      SUV
10  2021  Audi          S5  Convertible,Sedan,Coupe
11  2021  Audi          S6                    Sedan

In [100]:
print('Select the LAST 10 observations and only the variable "Year" from the dataframe')
carmodels["Year"].tail(10)

Select the LAST 10 observations and only the variable "Year" from the dataframe

230    2021
231    2021
232    2021
233    2021
234    2021
235    2021
236    2021
237    2021
238    2021
239    2021
Name: Year, dtype: int64

## MERGING DATAFRAME - by rows ##

In [113]:
print('Create data 1 using a dictionary')
data1 = {'Customer ID':[1,2],'Product':['TV', 'Oven']}
df1 = pd.DataFrame(data1)
display (df1)

Create data 1 using a dictionary

   Customer ID Product
0            1      TV
1            2    Oven

In [114]:
print('Create data 2 using a dictionary')
data2 = {'Customer ID':[3,4],'Product':['Oven','TV']}
df2 = pd.DataFrame(data2)
display (df2)

Create data 2 using a dictionary

   Customer ID Product
0            3    Oven
1            4      TV

In [116]:
print('CONCAT data 1 and data 2 together. NOTE THE INDEX FOR THE ROWS')
df3 = pd.concat([df1,df2])
display (df3)

CONCAT data 1 and data 2 together. NOTE THE INDEX FOR THE ROWS

   Customer ID Product
0            1      TV
1            2    Oven
0            3    Oven
1            4      TV

In [117]:
print('CONCAT data 1 and data 2 together, BUT keep the index for the rows in a consecutive manner. Type "ignore_index = True"')
df4 = pd.concat([df1,df2], ignore_index=True)
display (df4)

CONCAT data 1 and data 2 together, BUT keep the index for the rows in a consecutive manner. Type "ignore_index = True"

   Customer ID Product
0            1      TV
1            2    Oven
2            3    Oven
3            4      TV

## MERGING DATAFRAME - natural join: return the rows where 2 dataframes have matching keys ##

In [125]:
data5 = {'Customer ID':[1,2,3,4,5],'Product':['TV','TV','TV','Oven','Oven']}
df5 = pd.DataFrame(data5)
display (df5)

data6 = {'Customer ID':[2,4,6,7],'Shop':['Shop_A','Shop_A','Shop_B','Shop_C']}
df6 = pd.DataFrame(data6)
display (df6)

   Customer ID Product
0            1      TV
1            2      TV
2            3      TV
3            4    Oven
4            5    Oven

   Customer ID    Shop
0            2  Shop_A
1            4  Shop_A
2            6  Shop_B
3            7  Shop_C

In [128]:
print('Select data using INNER JOIN based on Customer ID. Only Customer ID 2 and 4 showed up in both dataframes.')
inner_df = pd.merge(df5, df6, on='Customer ID', how='inner')
display (inner_df)

Select data using INNER JOIN based on Customer ID. Only Customer ID 2 and 4 showed up in both dataframes.

   Customer ID Product    Shop
0            2      TV  Shop_A
1            4    Oven  Shop_A

## MISSING DATA & OUTLIERS - find missing values ##

In [146]:
c_imports = pd.read_csv('fruits_corrupted.csv')
print('Notice how Apple prices is NaN = Not a Number')
c_imports

Notice how Apple prices is NaN = Not a Number

   Fruits  Prices      Country
0   Apple     NaN       Africa
1  Orange     0.7       Russia
2  Banana     0.9  New Zealand

In [134]:
print('To check every cell in the dataframe and returns TRUE if the cell contains a missing value. TRUE = Missing value FALSE = Value exist')
c_imports.isnull()

To check every cell in the dataframe and returns TRUE if the cell contains a missing value. TRUE = Missing value FALSE = Value exist

   Fruits  Prices  Country
0   False    True    False
1   False   False    False
2   False   False    False

In [139]:
print('is.null returns TRUE for missing values. .sum adds up all the TRUE , counting the number of missing values')
print('axis = 0 will count the columns . The results below shows "Prices" has 1 TRUE aka missing value')
c_imports.isnull().sum(axis=0)

is.null returns TRUE for missing values. .sum adds up all the TRUE , counting the number of missing values
axis = 0 will count the columns . The results below shows "Prices" has 1 TRUE aka missing value

Fruits     0
Prices     1
Country    0
dtype: int64

In [142]:
print('is.null returns TRUE for missing values. .sum adds up all the TRUE , counting the number of missing values')
print('axis = 1 will count the rows. The results below show row 0 has 1 TRUE aka missing value')
c_imports.isnull().sum(axis=1)

is.null returns TRUE for missing values. .sum adds up all the TRUE , counting the number of missing values
axis = 1 will count the rows. The results below show row 0 has 1 TRUE aka missing value

0    1
1    0
2    0
dtype: int64

In [154]:
print('is.null().any(axis __) is used to check whether ANY missing data exist')
c_imports.isnull().any()

is.null().any(axis __) is used to check whether ANY missing data exist

Fruits     False
Prices      True
Country    False
dtype: bool

In [167]:
print('Create a variable called missing_cimport to represent the missing values.')
missing_cimport = c_imports.isnull().any()
print('use == True.index to specifically identify WHICH index from the columns has missing values.')
missing_cimport [missing_cimport == True].index

Create a variable called missing_cimport to represent the missing values.
use == True.index to specifically identify WHICH index from the columns has missing values.

Index(['Prices'], dtype='object')

## MISSING DATA & OUTLIERS - replace missing values ##

In [161]:
price_mean = c_imports['Prices'].mean()

In [168]:
print('Replace missing values by using .fillna()')
c_imports['Prices'].fillna(value=price_mean)

Replace missing values by using .fillna()

0    0.8
1    0.7
2    0.9
Name: Prices, dtype: float64

## MISSING DATA & OUTLIERS - deleting missing data ##

In [179]:
print('.drop is used to specify the ROW INDICES with missing values that should be removed.')
c_imports.drop(axis=0, index = [0])

.drop is used to specify the ROW INDICES with missing values that should be removed.

   Fruits  Prices      Country
1  Orange     0.7       Russia
2  Banana     0.9  New Zealand

In [192]:
print('.dropna is to drop the missing values. axis = 0(rows) 1(columns). how = "all" means to remove if ALL VALUES ARE MISSING')
print('results show to drop the columns if ALL values in the column is missing. NO COLUMN IS HAS ALL MISSING VALUES')
c_imports.dropna(axis=1, how="all")

.dropna is to drop the missing values. axis = 0(rows) 1(columns). how = "all" means to remove if ALL VALUES ARE MISSING
results show to drop the columns if ALL values in the column is missing. NO COLUMN IS HAS ALL MISSING VALUES

   Fruits  Prices      Country
0   Apple     NaN       Africa
1  Orange     0.7       Russia
2  Banana     0.9  New Zealand

In [195]:
print('how = "any" means to remove if ANY VALUES ARE MISSING. ROW 0 IS REMOVED BECAUSE THERE IS ONE MISSING VALUE')
c_imports.dropna(axis=0, how="any")

how = "any" means to remove if ANY VALUES ARE MISSING. ROW 0 IS REMOVED BECAUSE THERE IS ONE MISSING VALUE

   Fruits  Prices      Country
1  Orange     0.7       Russia
2  Banana     0.9  New Zealand

## OUTLIERS ##