**Seminar 2 Discussion Board**

*Group 6 - Shi En , Zenda , Arsyad , Mageswaran*

1.   Display the raw data values
2.   Report the missing values
3.   Describe the statistical summaries
4.   Detect the outliers

In [19]:
import pandas as pd

# Display the raw data values
df = pd.read_csv("MissingValue.csv")
df.set_index('ID',inplace=True)
display(df)

    INCOME  LOAN  EXPENDITURE
ID
1      NaN   500         1400
2   4000.0   250         2000
3      NaN   400         1000
4   1500.0   200          750
5   4500.0   650         3000
6   3500.0   700         3000
7   2800.0   400         2500
8   7000.0   800         4000
9   5400.0   800         3500
10  6000.0   850         4500

In [36]:
# Report the missing values
display(df.isnull())
display(df[df.isnull().any(axis=1)])

    INCOME   LOAN  EXPENDITURE
ID
1     True  False        False
2    False  False        False
3     True  False        False
4    False  False        False
5    False  False        False
6    False  False        False
7    False  False        False
8    False  False        False
9    False  False        False
10   False  False        False

    INCOME  LOAN  EXPENDITURE
ID
1      NaN   500         1400
3      NaN   400         1000

In [41]:
# Describe the statistical summaries
df.describe(include='all')

            INCOME        LOAN  EXPENDITURE
count     8.000000   10.000000    10.000000
mean   4337.500000  555.000000  2565.000000
std    1782.404075  237.404952  1268.430789
min    1500.000000  200.000000   750.000000
25%    3325.000000  400.000000  1550.000000
50%    4250.000000  575.000000  2750.000000
75%    5550.000000  775.000000  3375.000000
max    7000.000000  850.000000  4500.000000

In [61]:
import pandas as pd

# Detect the outliers
df_outlier = pd.read_csv('MissingValue_Outlier.csv')
df_outlier.set_index('ID', inplace=True)
display(df_outlier)

Q1 = df_outlier.quantile(0.25)
Q3 = df_outlier.quantile(0.75)
IQR = Q3-Q1
lower_bound = Q1-(1.5*IQR)
upper_bound = Q3+(1.5*IQR)
outliers = (df_outlier < lower_bound)|(df_outlier > upper_bound)

display(df_outlier[outliers.any(axis=1)])
print('This outlier is ID 10')

    INCOME  LOAN  EXPENDITURE
ID
1      NaN   500         1400
2   4000.0   250         2000
3      NaN   400         1000
4   1500.0   200          750
5   4500.0   650         3000
6   3500.0   700         3000
7   2800.0   400         2500
8   7000.0   800         4000
9   5400.0   800         3500
10  6000.0   850        10000

    INCOME  LOAN  EXPENDITURE
ID
10  6000.0   850        10000

This outlier is ID 10